In [1]:
import requests
from requests import get
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

In [2]:
headers = {"Accept-Language": "en-US, en;q=0.5"}
driver = webdriver.Chrome(ChromeDriverManager().install())

====== WebDriver manager ======
Current google-chrome version is 91.0.4472
Get LATEST driver version for 91.0.4472
Driver [C:\Users\yfird\.wdm\drivers\chromedriver\win32\91.0.4472.101\chromedriver.exe] found in cache

In [10]:
Name=[]
Price=[]

urls=["https://mile12mart.com/product-category/fruits/","https://mile12mart.com/product-category/meat/","https://mile12mart.com/product-category/pepper/","https://mile12mart.com/product-category/tubers/","https://mile12mart.com/product-category/vegetables/","https://mile12mart.com/product-category/grains/"]
for url in urls:
    driver.get(url)
    results = driver.page_source
    soup = BeautifulSoup(results,"lxml")

    products=soup.find_all('div', class_="iq-product-title-price-holder")
    for item in products:
        name=item.h5.text
        Name.append(name)
        #print(Name)
        #price
        for p in soup.find_all('div', class_="iq-pricing-details"): 
            price=p.findAll('span')[0].text.strip()
        if price is not None:
             price= price   
        else:
             price = np.nan
        Price.append(price)
        #print(Price)

In [11]:
items=pd.DataFrame({
    'Name':Name,
    'Price':Price
})

In [12]:
items.shape

(53, 2)

In [13]:
items.head()

                         Name  Price
0    Apple- SmallSize- 20pcs   ₦1200
1          Avocado- 12Pieces   ₦1200
2            Coconut  12 pcs   ₦1200
3              Grape  25 pcs   ₦1200
4              Grape  50 pcs   ₦1200

In [14]:
items.isnull()

     Name  Price
0   False  False
1   False  False
2   False  False
3   False  False
4   False  False
5   False  False
6   False  False
7   False  False
8   False  False
9   False  False
10  False  False
11  False  False
12  False  False
13  False  False
14  False  False
15  False  False
16  False  False
17  False  False
18  False  False
19  False  False
20  False  False
21  False  False
22  False  False
23  False  False
24  False  False
25  False  False
26  False  False
27  False  False
28  False  False
29  False  False
30  False  False
31  False  False
32  False  False
33  False  False
34  False  False
35  False  False
36  False  False
37  False  False
38  False  False
39  False  False
40  False  False
41  False  False
42  False  False
43  False  False
44  False  False
45  False  False
46  False  False
47  False  False
48  False  False
49  False  False
50  False  False
51  False  False
52  False  False

In [15]:
items.duplicated().any().sum()

0

In [16]:
items.to_csv("Mile12market.csv",index=False)